<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPsxpbxx\installerProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPsxpbxx/installerProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPsxpbxx.legacy');

    return;
}

if (!\class_exists(installerProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPsxpbxx\installerProdDebugProjectContainer::class, installerProdDebugProjectContainer::class, false);
}

return new \ContainerPsxpbxx\installerProdDebugProjectContainer(array(
    'container.build_hash' => 'Psxpbxx',
    'container.build_id' => '28f6947d',
    'container.build_time' => 1532336814,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPsxpbxx');
