<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.tabbed_slider_text' shared autowired service.

$this->services['app.area.brick.tabbed_slider_text'] = $instance = new \AppBundle\Document\Areabrick\TabbedSliderText();

$instance->setContainer($this);

return $instance;
