<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.horizontal_line' shared autowired service.

$this->services['app.area.brick.horizontal_line'] = $instance = new \AppBundle\Document\Areabrick\HorizontalLine();

$instance->setContainer($this);

return $instance;
