<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.image_hotspot_marker' shared autowired service.

$this->services['app.area.brick.image_hotspot_marker'] = $instance = new \AppBundle\Document\Areabrick\ImageHotspotMarker();

$instance->setContainer($this);

return $instance;
