<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Sitemap\Element\Processor\ModificationDateProcessor' shared autowired service.

return $this->services['Pimcore\Sitemap\Element\Processor\ModificationDateProcessor'] = new \Pimcore\Sitemap\Element\Processor\ModificationDateProcessor();
