<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.provider_handler' shared service.

if ($lazyLoad) {
    return $this->privates['scheb_two_factor.provider_handler'] = $this->createProxy('TwoFactorProviderHandler_3ecff6c', function () {
        return \TwoFactorProviderHandler_3ecff6c::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSchebTwoFactor_ProviderHandlerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\TwoFactorProviderHandler(${($_ = isset($this->services['scheb_two_factor.provider_registry']) ? $this->services['scheb_two_factor.provider_registry'] : $this->load('getSchebTwoFactor_ProviderRegistryService.php')) && false ?: '_'});
