<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.security.google' shared service.

return $this->services['scheb_two_factor.security.google'] = new \Google\Authenticator\GoogleAuthenticator();
