<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scheb_two_factor.firewall_context' shared service.

return $this->services['scheb_two_factor.firewall_context'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\TwoFactorFirewallContext(array('admin' => ${($_ = isset($this->services['security.firewall_config.two_factor.admin']) ? $this->services['security.firewall_config.two_factor.admin'] : $this->load('getSecurity_FirewallConfig_TwoFactor_AdminService.php')) && false ?: '_'}));
