<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'scheb_two_factor.security.google_authenticator' shared service.

return $this->services['scheb_two_factor.security.google_authenticator'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Provider\Google\GoogleAuthenticator(${($_ = isset($this->services['scheb_two_factor.security.google']) ? $this->services['scheb_two_factor.security.google'] : $this->services['scheb_two_factor.security.google'] = new \Google\Authenticator\GoogleAuthenticator()) && false ?: '_'}, 'Pimcore', 'Pimcore 2 Factor Authentication');
