<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.null_trusted_device_manager' shared service.

return $this->services['scheb_two_factor.null_trusted_device_manager'] = new \Scheb\TwoFactorBundle\Security\TwoFactor\Trusted\NullTrustedDeviceManager();
