<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.persister_factory.doctrine' shared service.

return $this->services['scheb_two_factor.persister_factory.doctrine'] = new \Scheb\TwoFactorBundle\Model\Persister\DoctrinePersisterFactory(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, NULL);
