<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrfdluy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrfdluy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerDrfdluy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerDrfdluy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerDrfdluy\appProdProjectContainer(array(
    'container.build_hash' => 'Drfdluy',
    'container.build_id' => '23c437e9',
    'container.build_time' => 1532337010,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrfdluy');
