<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.wysiwyg_with_images' shared autowired service.

$this->services['app.area.brick.wysiwyg_with_images'] = $instance = new \AppBundle\Document\Areabrick\WysiwygWithImages();

$instance->setContainer($this);

return $instance;
