<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.text_accordion' shared autowired service.

$this->services['app.area.brick.text_accordion'] = $instance = new \AppBundle\Document\Areabrick\TextAccordion();

$instance->setContainer($this);

return $instance;
