<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.area.brick.icon_teaser_row' shared autowired service.

$this->services['app.area.brick.icon_teaser_row'] = $instance = new \AppBundle\Document\Areabrick\IconTeaserRow();

$instance->setContainer($this);

return $instance;
