<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Document\Areabrick\Blockquote' shared autowired service.

$this->services['AppBundle\Document\Areabrick\Blockquote'] = $instance = new \AppBundle\Document\Areabrick\Blockquote();

$instance->setContainer($this);

return $instance;
