<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\DataObject\Import\Resolver\Code' shared autowired service.

return $this->services['Pimcore\DataObject\Import\Resolver\Code'] = new \Pimcore\DataObject\Import\Resolver\Code(${($_ = isset($this->services['Pimcore\Localization\LocaleService']) ? $this->services['Pimcore\Localization\LocaleService'] : $this->load('getLocaleServiceService.php')) && false ?: '_'});
