<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Templating\Helper\LanguageSwitcher' shared autowired service.

return $this->services['AppBundle\Templating\Helper\LanguageSwitcher'] = new \AppBundle\Templating\Helper\LanguageSwitcher(${($_ = isset($this->services['Pimcore\Model\Document\Service']) ? $this->services['Pimcore\Model\Document\Service'] : $this->services['Pimcore\Model\Document\Service'] = new \Pimcore\Model\Document\Service()) && false ?: '_'});
