<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Sitemap\Element\Filter\PropertiesFilter' shared autowired service.

return $this->services['Pimcore\Sitemap\Element\Filter\PropertiesFilter'] = new \Pimcore\Sitemap\Element\Filter\PropertiesFilter();
