<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.persister.doctrine' shared service.

if ($lazyLoad) {
    return $this->privates['scheb_two_factor.persister.doctrine'] = $this->createProxy('DoctrinePersister_a694024', function () {
        return \DoctrinePersister_a694024::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSchebTwoFactor_Persister_DoctrineService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return ${($_ = isset($this->services['scheb_two_factor.persister_factory.doctrine']) ? $this->services['scheb_two_factor.persister_factory.doctrine'] : $this->load('getSchebTwoFactor_PersisterFactory_DoctrineService.php')) && false ?: '_'}->getPersister();
