<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.qyiysja' shared service.

return $this->services['service_locator.qyiysja'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('eventDispatcher' => function () {
    return ${($_ = isset($this->services['event_dispatcher']) ? $this->services['event_dispatcher'] : $this->getEventDispatcherService()) && false ?: '_'};
}, 'importService' => function () {
    $f = function (\Pimcore\DataObject\Import\Service $v = null) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\DataObject\Import\Service']) ? $this->services['Pimcore\DataObject\Import\Service'] : $this->load('getService4Service.php')) && false ?: '_'});
}, 'localeService' => function () {
    $f = function (\Pimcore\Localization\LocaleServiceInterface $v) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Localization\LocaleService']) ? $this->services['Pimcore\Localization\LocaleService'] : $this->load('getLocaleServiceService.php')) && false ?: '_'});
}, 'modelFactory' => function () {
    return ${($_ = isset($this->services['Pimcore\Model\Factory']) ? $this->services['Pimcore\Model\Factory'] : $this->load('getFactoryService.php')) && false ?: '_'};
}));
