<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access.authenticated_voter' shared service.

return $this->services['security.access.authenticated_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter(${($_ = isset($this->services['scheb_two_factor.security.authentication.trust_resolver']) ? $this->services['scheb_two_factor.security.authentication.trust_resolver'] : $this->getSchebTwoFactor_Security_Authentication_TrustResolverService()) && false ?: '_'});
