<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.iwwuhoe' shared service.

return $this->services['service_locator.iwwuhoe'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('actionRenderer' => function () {
    return ${($_ = isset($this->services['pimcore.templating.action_renderer']) ? $this->services['pimcore.templating.action_renderer'] : $this->getPimcore_Templating_ActionRendererService()) && false ?: '_'};
}, 'localeService' => function () {
    $f = function (\Pimcore\Localization\LocaleServiceInterface $v) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Localization\LocaleService']) ? $this->services['Pimcore\Localization\LocaleService'] : $this->load('getLocaleServiceService.php')) && false ?: '_'});
}, 'tagHandler' => function () {
    return ${($_ = isset($this->services['Pimcore\Document\Tag\DelegatingTagHandler']) ? $this->services['Pimcore\Document\Tag\DelegatingTagHandler'] : $this->load('getDelegatingTagHandlerService.php')) && false ?: '_'};
}));
