<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'scheb_two_factor.authenticated_token_handler' shared service.

if ($lazyLoad) {
    return $this->privates['scheb_two_factor.authenticated_token_handler'] = $this->createProxy('AuthenticatedTokenHandler_e3677d3', function () {
        return \AuthenticatedTokenHandler_e3677d3::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSchebTwoFactor_AuthenticatedTokenHandlerService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

return new \Scheb\TwoFactorBundle\Security\TwoFactor\Handler\AuthenticatedTokenHandler(${($_ = isset($this->services['scheb_two_factor.ip_whitelist_handler']) ? $this->services['scheb_two_factor.ip_whitelist_handler'] : $this->load('getSchebTwoFactor_IpWhitelistHandlerService.php')) && false ?: '_'}, $this->parameters['scheb_two_factor.security_tokens']);
