<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.se7cmaa' shared service.

return $this->services['service_locator.se7cmaa'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('localeService' => function () {
    $f = function (\Pimcore\Localization\LocaleServiceInterface $v) { return $v; }; return $f(${($_ = isset($this->services['Pimcore\Localization\LocaleService']) ? $this->services['Pimcore\Localization\LocaleService'] : $this->load('getLocaleServiceService.php')) && false ?: '_'});
}));
