<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Pimcore\Sitemap\UrlGenerator' shared autowired service.

return $this->services['Pimcore\Sitemap\UrlGenerator'] = new \Pimcore\Sitemap\UrlGenerator(${($_ = isset($this->services['pimcore.routing.router.request_context']) ? $this->services['pimcore.routing.router.request_context'] : $this->getPimcore_Routing_Router_RequestContextService()) && false ?: '_'});
